CREATE SCHEMA IF NOT EXISTS warehouse;

CREATE TABLE warehouse.warehouse_products (
    product_id UUID PRIMARY KEY,
    quantity BIGINT NOT NULL DEFAULT 0,
    fragile BOOLEAN DEFAULT FALSE,
    width DOUBLE PRECISION,
    height DOUBLE PRECISION,
    depth DOUBLE PRECISION,
    weight DOUBLE PRECISION
);

CREATE TABLE warehouse.warehouse_addresses (
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    warehouse_code VARCHAR(50) UNIQUE NOT NULL,
    country VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    street VARCHAR(200) NOT NULL,
    house VARCHAR(20) NOT NULL,
    flat VARCHAR(20),
    is_active BOOLEAN DEFAULT TRUE
);